version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    depends_on:
      - "postgres"
    restart: on-failure
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - $DB_PORT:$DB_PORT
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 3s
      timeout: 5s
      retries: 10
