# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x06\n\x04Null\"(\n\x07\x41\x64\x64\x41rgs\x12\r\n\x05\x66irst\x18\x01 \x01(\x05\x12\x0e\n\x06second\x18\x02 \x01(\x05\"\x1a\n\x08\x41\x64\x64Reply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x42\n\nAddService\x12\x16\n\x06Health\x12\x05.Null\x1a\x05.Null\x12\x1c\n\x03\x41\x64\x64\x12\x08.AddArgs\x1a\t.AddReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=17
  _NULL._serialized_end=23
  _ADDARGS._serialized_start=25
  _ADDARGS._serialized_end=65
  _ADDREPLY._serialized_start=67
  _ADDREPLY._serialized_end=93
  _ADDSERVICE._serialized_start=95
  _ADDSERVICE._serialized_end=161
# @@protoc_insertion_point(module_scope)
